sudo: false
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master
#
# services:
#
# matrix:
#  include:
#    - os: linux

env:
   
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - mkdir -p $HOME/.mantid
  - echo "default.facility=SNS" > $HOME/.mantid/Mantid.user.properties

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda create -n testenv pip pytest python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv numpy scipy matplotlib
  - conda install -n testenv -c mcvine histogram
  - conda install -n testenv -c neutrons ipywe
  - conda install -n testenv -c mantid mantid-framework
  - source activate testenv
  - python setup.py install
#  - pip install coveralls
#  - pip install codecov

script:
   - py.test
   - travis_wait 40 python tests/getdos_TestCase.py
   - travis_wait 20 python tests/getdos_TestCase2.py
   - travis_wait 20 python tests/ui/batch_TestCase.py

notifications:
  email:
    on_success: change
    on_failure: always
