name: multiphonon_conda
channels:
  - conda-forge
  - mcvine
  - mantid
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - libmamba
  - libarchive
  - python-build
  - versioningit
  - setuptools
