name: multiphonon
channels:
  - conda-forge
  - mcvine
  - mantid
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - conda-build
  - coverage
  - histogram == 0.3.9
  - numpy == 1.20.3
  - scipy == 1.9.0
  - python ==3.8
  - pyre == 0.8.3
  - mantid == 6.4
  - matplotlib
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - versioningit
  - setuptools
  - coveralls
  - ipywidgets # used in one test
  - pip
  - pip:
    - ipywe == 0.1.3a1
