name: multiphonon
channels:
  - conda-forge
  - mcvine
  - mantid
dependencies:
  - anaconda-client
  - boa
  - conda-build < 4
  - coverage
  - python = 3.9
  - boost
  - numpy
  - scipy
  - histogram
  - matplotlib
  - pyre
  - mantid-framework
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - versioningit
  - setuptools
  - coveralls
  - pip
  - pip:
    - ipywe == 0.1.3a1
