#default environment for installing python package
#Note: Use this
name: multiphonon
channels:
  - mantid
  - neutrons/label/rc
  - mcvine
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - coverage
  - numpy == 1.26.4
  - scipy == 1.14.1
  - python >=3.10
  - pyre == 0.8.3
  - mantid
  - matplotlib
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - sphinx
  - sphinx-rtd-theme
  - numpydoc
  - versioningit
  - setuptools
  - coveralls
  - ipywidgets # used in one test
  - histogram
