#default environment for installing python package
#Note: Use this
name: multiphonon
channels:
  - mantid
  - mcvine
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - coverage
  - numpy >= 1.20.3
  - scipy >= 1.9.0
  - python
  - pyre == 0.8.3
  - mantid
  - matplotlib
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - sphinx
  - sphinx-rtd-theme
  - numpydoc
  - versioningit
  - setuptools
  - coveralls
  - ipywidgets # used in one test
  - pip
  - pip:
    - ipywe == 0.1.3a1
    - git+https://github.com/neutrons/histogram-dev.git@next#egg=histogram-dev
