name: multiphonon
channels:
  - conda-forge
  - mcvine
  - mantid
dependencies:
  - anaconda-client
  - boa
  - conda-build < 4
  - coverage
  - python
  - numpy = 1.20.3
  - scipy = 1.9.0
  - histogram = 0.3.9
  - matplotlib
  - pyre = 0.8.3
  - mantid-framework = 6.3
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - versioningit
  - setuptools
  - coveralls
  - pip
  - pip:
    - ipywe==0.1.3a1
