name: multiphonon
channels:
  - conda-forge
  - mcvine
  - mantid
dependencies:
  - anaconda-client
  - boa
  - conda-build < 4
  - coverage
  - histogram
  - numpy
  - scipy
  - python
  - pyre
  - mantid == 6.5
  - matplotlib
  - libmamba
  - libarchive
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - versioningit
  - setuptools
  - coveralls
  - ipywidgets # used in one test
  - pip
  - pip:
    - ipywe == 0.1.3a1
