package:
  name: multiphonon
  version: "0.1.6"

source:
  git_rev: v0.1.6
  git_url: https://github.com/neutrons/multiphonon.git

requirements:
  build:
    - python
    - numpy
    - scipy

  run:
    - python
    - numpy
    - histogram
    - scipy
    - matplotlib
    - pytest
    - pyyaml
    - mantid
#    - ipywe

build:
  noarch: python
  script_env:

test:
  imports:
    - multiphonon

about:
  home:
  license:
  license_file:
